name: Melodic CI

on:
  push:
    branches-ignore:
      - "humble**"
  pull_request:
    branches-ignore:
      - "humble**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker setup and build
        run: docker build . -t mesh_nav/melodic -f ci/Dockerfile-melodic
      - name: catkin lint
        run: docker run mesh_nav/melodic catkin_lint src
